project_name: firestore-repo

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: cmd/firestore-repo
    binary: firestore-repo
    ldflags:
      - -s -w
      - -X github.com/go-generalize/firestore-repo/main.AppVersion={{ .Version }}
    env:
      - CGO_ENABLED=0

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

release:
  prerelease: auto
