name: Go

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      firestore:
        image: google/cloud-sdk
        ports:
          - 8000:8000
        options: -ti

    env:
      GO111MODULE: on
      FIRESTORE_EMULATOR_HOST: 127.0.0.1:8000

    steps:
      - name: Install firestore emulator
        run: docker exec $(docker ps -f "ancestor=google/cloud-sdk" -q) apt install -y google-cloud-sdk-firestore-emulator
      - name: Start firestore emulator
        run: docker exec -d $(docker ps -f "ancestor=google/cloud-sdk" -q) gcloud beta emulators firestore start --project=pname --host-port 0.0.0.0:8000

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - uses: actions/checkout@v2

      - name: Make statik
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get github.com/rakyll/statik
          make statik

      - name: Run tests
        run: |
          make test TEST_OPT='-tags="emulator"'
